"""add bynder asset cache table

Revision ID: 3b14c4df690c
Revises: b4741391fd2e
Create Date: 2026-04-27 12:32:40.766055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b14c4df690c'
down_revision: Union[str, None] = 'b4741391fd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentup_image_bynder_asset_cache',
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('assets_json', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contentup_image_bynder_asset_cache')
    # ### end Alembic commands ###
