"""initial contentup_image tables

Revision ID: b4741391fd2e
Revises: 
Create Date: 2026-04-21 10:28:48.061559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4741391fd2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentup_image_package_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('packaged_by', sa.Text(), nullable=True),
    sa.Column('slot_manifest', sa.JSON(), nullable=True),
    sa.Column('zip_filename', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contentup_image_product_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contentup_image_sku_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('amazon_slot', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('bynder_asset_id', sa.Text(), nullable=True),
    sa.Column('uploaded_file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('bynder', 'upload')", name='source_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', 'amazon_slot')
    )
    op.create_table('contentup_image_filename_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.Column('regex', sa.Text(), nullable=False),
    sa.Column('sample_filename', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['contentup_image_product_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contentup_image_filename_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.Column('position_label', sa.Text(), nullable=False),
    sa.Column('amazon_slot', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['contentup_image_product_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_line_id', 'position_label')
    )
    op.create_table('contentup_image_infographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('amazon_slot', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['contentup_image_product_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contentup_image_infographics')
    op.drop_table('contentup_image_filename_rules')
    op.drop_table('contentup_image_filename_patterns')
    op.drop_table('contentup_image_sku_overrides')
    op.drop_table('contentup_image_product_lines')
    op.drop_table('contentup_image_package_history')
    # ### end Alembic commands ###
